use_default_settings: true

server:
  secret_key: "__SEARXNG_SECRET__"

search:
  formats:
    - html
    - json

doi_resolvers:
  oadoi.org: "https://oadoi.org/"
  doi.org: "https://doi.org/"
  doai.io: "https://dissem.in/"
  sci-hub.se: "https://sci-hub.se/"
  sci-hub.st: "https://sci-hub.st/"
  sci-hub.ru: "https://sci-hub.ru/"
default_doi_resolver: "oadoi.org"
